# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "main", "develop" ]
    # paths:
    #   - AgileWorksAPI/**
    #   - .github/workflows/dotnet-project.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x   
    - name: Add Test project reference to main project
      run : dotnet add AgileWorksAPI.Tests/AgileWorksAPI.Tests.csproj reference AgileWorksAPI/AgileWorksAPI.csproj    
    - name: Install dependencies for Project
      run: |
        cd AgileworksAPI
        dotnet add package Microsoft.EntityFrameworkCore.InMemory                   
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
