# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "main", "develop" ]
    paths: 
      - AgileworksAPI/**
      - AgileWorksAPI.Tests/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x   
    - name: Install dependencies for Project
      run: |
        cd AgileworksAPI
        dotnet add package Microsoft.EntityFrameworkCore.InMemory                   
    - name: Build
      run: |
        cd AgileworksAPI      
        dotnet build --no-restore
        dotnet new classlib -o AgileworksAPI
    - name: Add Test project reference to main project
      run : |
        cd AgileWorksAPI.Tests
        dotnet add AgileWorksAPI.Tests.csproj reference ../AgileworksAPI/AgileworksAPI.csproj   
    - name: Test
      run: |
        cd "AgileWorksAPI.Tests"
        dotnet test --verbosity normal
